name: germany_crude_oil_trade
version: "1.0.0"
config-version: 2

profile: germany_crude_oil_trade

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]

models:
  germany_crude_oil_trade:
    staging:
      +materialized: view
    marts:
      +materialized: table
    facts:
      +materialized: table

